# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: 
      - master
      - dev
      - pr/** 
  pull_request:
    branches: 
      - master
      - dev
      - pr/** 

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a perl version
      - uses: shogo82148/actions-setup-perl@v1
        with:
           perl-version: '5.10'

      - name: before install
        run: |
          cpanm --local-lib=~/perl5 local::lib && eval $(perl -I ~/perl5/lib/perl5/ -Mlocal::lib)
          cpanm --notest Perl::Tidy
          cpanm --notest Test::Code::TidyAll
      
      - name: install
        run: |
          cpanm --quiet --installdeps --notest --force --skip-satisfied .
      
      - name: script
        run: |
          perl Build.PL && ./Build build && ./Build test
          
      - name: after success
        run: |
          cpanm --quiet --notest --skip-satisfied Devel::Cover::Report::Coveralls
